# This is a basic workflow to help you get started with Actions

name: CI

#  Controls when workflow will run
on:
  #Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
  #Allow you to run this workflow manually from Actions tab
  workflow_dispatch:
  
# A workflow run made up of one more jobs that can run sequentially or in parallel
jobs:
  #This workflow contains a silge job called "build"
  build:
    # The type of runner that the job will run on
    name: Exploring GitHub Actions
    runs-on: self-hosted
    
    # Steps represent a sequence of tasks that will be wxecuted as part of the job
    steps:
      # Checks-out you repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      #Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      #Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: 
          echo Add other actions to build,
          echo test, and deploy yout project.
